name: lofiii
description: "Music Streaming App"
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 2.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  bloc:
  dio: ^5.4.1
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  path_provider: ^2.1.2
  lottie: ^3.1.0
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  gap: ^3.0.1
  nested:
  eva_icons_flutter: ^3.1.0
  just_audio: ^0.9.36
  animate_do: ^3.3.3
  connectivity_plus: ^5.0.2
  top_snackbar_flutter: ^3.1.0
  fast_cached_network_image: ^1.2.7
  volume_controller: ^2.0.7
  palette_generator: ^0.3.3+3
  hive: ^2.2.3
  like_button: ^2.0.5
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.0
  rxdart: ^0.27.7
  wakelock_plus: ^1.1.4
  border_progress_indicator: ^0.0.3
  flutter_flip_card: ^0.0.5
  percent_indicator: ^4.2.3
  flutter_media_downloader: ^1.0.4
  on_audio_query: ^2.9.0
  device_info_plus: ^9.1.2
  mini_music_visualizer: ^1.1.0
  one_context: ^4.0.0
  animated_text_kit: ^4.2.2
  flutter_email_sender: ^6.0.2
  flutter_local_notifications: ^17.0.0
  get_it: ^7.6.7
  animated_react_button: ^0.0.4
  json_annotation: ^4.8.1
  # youtube_scrape_api: ^0.0.6
  pod_player: ^0.2.1
  signals: ^4.5.1
  floating: ^2.0.2
  shimmer: ^3.0.0
  flutter_background: ^1.2.0
  insta_image_viewer: ^1.0.4
  intl: ^0.19.0
  widget_and_text_animator: ^1.1.5
  just_audio_background: ^0.0.1-beta.13
  flutter_dotenv: ^5.1.0
  carousel_slider: ^5.0.0


dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Exo
      fonts:
        - asset: assets/fonts/Exo2-Black.ttf
        - asset: assets/fonts/Exo2-Medium.ttf
        - asset: assets/fonts/Exo2-Regular.ttf

